version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ott_user
      POSTGRES_PASSWORD: ott@3456
      POSTGRES_DB: ott_platform
    ports:
      - 5433:5432

#  keycloak:
#    image: quay.io/keycloak/keycloak:22.0.0
#    container_name: keycloak
#    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: password
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - 9090:8080
#    command: start-dev
#    depends_on:
#      - postgres
