version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: zenflix-postgres
    environment:
      POSTGRES_USER: REDACTED_USER
      POSTGRES_PASSWORD: REDACTED_PASSWORD
      POSTGRES_DB: zenflix_db
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenflix-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zenflix_db
      SPRING_DATASOURCE_USERNAME: REDACTED_USER
      SPRING_DATASOURCE_PASSWORD: REDACTED_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker

volumes:
  data: